ehpvendingmachine.MVC/Controllers/DashBoardsController.cs
namespace ehpvendingmachine.MVC.Controllers
{
    using ClassLibrary.Models;
    using System.Linq;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin, User")]
    public class DashBoardsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: DashBoards
        public ActionResult Index()
        {
            var modelProductCounted = db.Products.ToList();
            int countProduct = modelProductCounted.Count();

            var modelMachineCounted = db.Machines.ToList();
            int countMachine = modelMachineCounted.Count();

            var modelAssigMacCounted = db.AssignMachines.ToList();
            int countAMachine = modelAssigMacCounted.Count();

            var modelSellCounted = db.Sells.ToList();
            int countSell = modelSellCounted.Count();

            var modelAlertCounted = db.AlertTypes.ToList();
            int countAlert = modelAlertCounted.Count();

            var modelHistoricCounted = db.HistoricAlerts.ToList();
            int countHistoric = modelHistoricCounted.Count();

            var modelMachineRequestedCounted = db.RequestMachines.Where(x => x.Assigned == false).ToList();
            int countMachineRequested = modelMachineRequestedCounted.Count();

            var modelProductMachineCounted = db.ProductsMachines.GroupBy(p => p.ProductId);
            int countProductMachine = modelProductMachineCounted.Count();

            ViewBag.Message = "ehp Vending Machine Dashboard!";

            DashBoard myDashboard = new DashBoard
            {
                ProductCounted = countProduct,
                MachineCounted = countMachine,
                AssignedMachineCounted = countAMachine,
                SellsCounted = countSell,
                AlertCounted = countAlert,
                HistorcAlertCounted = countHistoric,
                MachinesRequestedCounted = countMachineRequested,
                ProductMachinesCounted = countProductMachine
            };

            return View(myDashboard);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ehpvendingmachine.MVC/Controllers/ProductReloadsController.cs
namespace ehpvendingmachine.MVC.Controllers
{
    using ClassLibrary.Models;
    using ClassLibrary.ViewModels;
    using Models;
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    [Authorize(Roles = "ProductsMachine Reload")]
    public class ProductReloadsController : Controller
    {

        DataContextLocal db = new DataContextLocal();

        // GET: ProductReloads
        [Authorize(Roles = "ProductsMachine Reload View")]
        public ActionResult Index(int? searchMachine)
        {
            ProductReloadViewModel productReloadViewModel = new ProductReloadViewModel();

            productReloadViewModel.ProductsMachines = db.ProductsMachines.OrderBy(p => p.MachineId).ToList();
            productReloadViewModel.Machines = db.Machines.ToList();

            // Carregar DropDownList com todas as maquina
            ViewBag.searchMachine = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString", searchMachine);

            if (!(searchMachine == null || searchMachine == 0))
            {
                productReloadViewModel.ProductsMachines = db.ProductsMachines.Where(m => m.MachineId == searchMachine).OrderBy(p => p.MachineId).ToList();
                productReloadViewModel.Machines = db.Machines.Where(m => m.MachineId == searchMachine).ToList();
            }

            return View(productReloadViewModel);

        }

        // GET: ProductReloads/AddAll
        [Authorize(Roles = "ProductsMachine Reload Add")]
        public ActionResult AddAll(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsMachine productsMachine = db.ProductsMachines.Find(id);
            if (productsMachine == null)
            {
                return HttpNotFound();
            }

            return View(productsMachine);
        }

        // POST: ProductReloads/AddAll
        [HttpPost, ActionName("AddAll")]
        [ValidateAntiForgeryToken]
        public ActionResult AddAllConfirmed(int id)
        {
            try
            {
                ProductsMachine productsMachine = db.ProductsMachines.Find(id);

                // Quantidade atual de produtos na máquina
                int currentQuantity = db.ProductsMachines.Where(m => m.MachineId == productsMachine.MachineId)
                    .Sum(m => m.ProductQuantity);

                // Apanhar capacidade limite da máquina
                Machine machine = db.Machines.Find(productsMachine.MachineId);

                int capacityLimit = db.Capacities.Find(machine.CapacityId).Quantity;

                productsMachine.ProductQuantity = productsMachine.ProductQuantity + (capacityLimit - currentQuantity);

                // Aletra campo altered para true
                productsMachine.Altered = true;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: ProductReloads/AddAll
        [Authorize(Roles = "ProductsMachine Reload Add")]
        public ActionResult AddxUn(int? id)
        {
            Session["productsMachine"] = null;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsMachine productsMachine = db.ProductsMachines.Find(id);
            if (productsMachine == null)
            {
                return HttpNotFound();
            }

            ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString", productsMachine.MachineId);
            ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name", productsMachine.ProductId);
            return View(productsMachine);
        }

        // POST: ProductReloads/AddxUn
        [HttpPost, ActionName("AddxUn")]
        [ValidateAntiForgeryToken]
        public ActionResult AddxUn([Bind(Include = "ProductsMachineId,MachineId,ProductId,ProductQuantity")] ProductsMachine productsMachine)
        {
            // Apanhar quantidade limite
            Machine machine = db.Machines.Find(productsMachine.MachineId);

            if (machine == null)
            {
                return HttpNotFound();
            }

            int capacityLimit = db.Capacities.Find(machine.CapacityId).Quantity;

            // Apanhar quantidade existente
            int currentQuantityTotal = db.ProductsMachines.AsNoTracking().Where(m => m.MachineId == productsMachine.MachineId).ToList()
                .Sum(m => m.ProductQuantity);

            // Adicionar à quantidade existente o que vem do utilizador
            int newQuantity = productsMachine.ProductQuantity + currentQuantityTotal;

            // Verificar se ao adicionar os produtos passa o limite da máquina
            if (newQuantity > capacityLimit)
            {
                ViewBag.Error = $"You can only enter more {capacityLimit - currentQuantityTotal} Un";

                ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString", productsMachine.MachineId);
                ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name", productsMachine.ProductId);
                return View(productsMachine);
            }

            // Apanhar a quantidade que já existe do produto na máquina
            int productQuantity = db.ProductsMachines.AsNoTracking().FirstOrDefault(p => p.ProductsMachineId ==productsMachine.ProductsMachineId).ProductQuantity;

            // Adicionar ao produto a quantidade do utilizador
            productsMachine.ProductQuantity = productsMachine.ProductQuantity + productQuantity;

            // Aletra campo altered para true
            productsMachine.Altered = true;

            // Preencher campo validade
            int validityDays = db.Products.FirstOrDefault(p => p.ProductId == productsMachine.ProductId).ValidityDays;
            productsMachine.ValidityDate = DateTime.Now.AddDays(validityDays);

            
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(productsMachine).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }

            ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString", productsMachine.MachineId);
            ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name", productsMachine.ProductId);
            return View(productsMachine);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ehpvendingmachine.MVC/Controllers/ProductsMachinesController.cs
namespace ehpvendingmachine.MVC.Controllers
{
    using ClassLibrary.Models;
    using Models;
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    [Authorize(Roles = "ProductsMachine")]
    public class ProductsMachinesController : Controller
    {
        private DataContextLocal db = new DataContextLocal();

        // GET: ProductsMachines
        [Authorize(Roles = "ProductsMachine View")]
        public ActionResult Index(int? searchMachine)
        {
            ViewBag.searchMachine = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString", searchMachine);

            var productsMachines = db.ProductsMachines.Include(p => p.Machine).Include(p => p.Product);

            if (!(searchMachine == null || searchMachine == 0))
            {
                productsMachines = db.ProductsMachines.Where(p => p.MachineId == searchMachine).Include(p => p.Machine).Include(p => p.Product);
            }

            return View(productsMachines.ToList().OrderBy(p => p.MachineId));

        }

        // GET: ProductsMachines/Create
        [Authorize(Roles = "ProductsMachine Create")]
        public ActionResult Create()
        {
            ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString");
            ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name");
            return View();
        }

        // POST: ProductsMachines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductsMachineId,MachineId,ProductId,ProductQuantity")] ProductsMachine productsMachine)
        {
            // Verificar Produto selecionado
            if (productsMachine.ProductId == 0)
            {
                ViewBag.Error = "You have to select a product";

                ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString");
                ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name");
                return View(productsMachine);
            }

            // Verificar Máquina selecionada
            if (productsMachine.MachineId == 0)
            {
                ViewBag.Error = "You have to select a machine";

                ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString");
                ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name");
                return View(productsMachine);
            }

            // Verificar se produto existe
            Product product = db.Products.Find(productsMachine.ProductId);
            if(product == null)
            {
                ViewBag.Error = "The product does not exist, make sure the product is created.";

                ViewBag.MachineId = new SelectList(db.Machines, "MachineId", "MachineId", productsMachine.MachineId);
                ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Name", productsMachine.ProductId);
                return View(productsMachine);
            }

            // Verificar se produto já existe na máquina
            var findProduct = db.ProductsMachines.FirstOrDefault(p => p.ProductId == productsMachine.ProductId && p.MachineId == productsMachine.MachineId);
            if (findProduct != null)
            {
                ViewBag.Error = "The product already exists on this machine";

                ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString");
                ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name");
                return View(productsMachine);
            }

            // Verificar se máquina existe
            Machine machine = db.Machines.Find(productsMachine.MachineId);
            if (machine == null)
            {
                ViewBag.Error = "The machine does not exist, make sure the machine is created.";

                ViewBag.MachineId = new SelectList(db.Machines, "MachineId", "MachineId", productsMachine.MachineId);
                ViewBag.ProductId = new SelectList(db.Products, "ProductId", "Name", productsMachine.ProductId);
                return View(productsMachine);
            }

            // Preencher campo quantidade a 0
            productsMachine.ProductQuantity = 0;

            // Preencher campo validade
            int validityDays = db.Products.FirstOrDefault(p => p.ProductId == productsMachine.ProductId).ValidityDays;

            productsMachine.ValidityDate = DateTime.Now.AddDays(validityDays);

            if (ModelState.IsValid)
            {
                try
                {
                    db.ProductsMachines.Add(productsMachine);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                
            }

            ViewBag.MachineId = new SelectList(Helpers.CombosHelper.GetMachinesList(), "MachineId", "MachineIdString");
            ViewBag.ProductId = new SelectList(Helpers.CombosHelper.GetProductsList(), "ProductId", "Name");
            return View(productsMachine);
        }

        // GET: ProductsMachines/Delete/5
        [Authorize(Roles = "ProductsMachine Delete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsMachine productsMachine = db.ProductsMachines.Find(id);
            if (productsMachine == null)
            {
                return HttpNotFound();
            }

            var productInSell = db.Sells.FirstOrDefault(p => p.ProductsMachineId == id);

            if (productInSell != null)
            {
                ViewBag.Error =
                    "The product can not be eliminated from the machine because there are sales associated with it.\nDisable the product so that it no longer appears on the machine";

                var productsMachines = db.ProductsMachines.Include(p => p.Machine).Include(p => p.Product);
                return View("Index", productsMachines.ToList());
            }

            return View(productsMachine);
        }

        // POST: ProductsMachines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductsMachine productsMachine = db.ProductsMachines.Find(id);

            if (productsMachine == null)
            {
                return HttpNotFound();
            }

            try
            {
                db.ProductsMachines.Remove(productsMachine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ehpvendingmachine.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ehp Vending Machine</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")


    @*Link's DataTanles*@
    <link rel="stylesheet" type="text/css" href="~/DataTables/datatables.min.css" />
    <script type="text/javascript" src="~/DataTables/datatables.min.js"></script>

    @Styles.Render("~/Content/csscustom")

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body onload="myFunction()">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ehp Vending Machine", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- MENU Dashboard -->
                    @if (User.IsInRole("Admin") || User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("DashBoard", "Index", "DashBoards")</li>
                    }
                    <!-- FIM MENU Dashboard -->
                    <!-- MENU MACHINES -->
                    @if (User.IsInRole("Machines Group"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Machines <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Capacities"))
                                {
                                    <li>@Html.ActionLink("Capacities", "Index", "Capacities")</li>
                                }
                                @if (User.IsInRole("Machines"))
                                {
                                    <li>@Html.ActionLink("Machines", "Index", "Machines")</li>
                                }
                                @if (User.IsInRole("CurrencyValues"))
                                {
                                    <li>@Html.ActionLink("Currency Values", "Index", "CurrencyValues")</li>
                                }
                                @if (User.IsInRole("Changes"))
                                {
                                    <li>@Html.ActionLink("Changes", "Index", "Changes")</li>
                                }
                                @if (User.IsInRole("ProductsMachine"))
                                {
                                    <li>@Html.ActionLink("Products Machines", "Index", "ProductsMachines")</li>
                                }
                                @if (User.IsInRole("AssignMachines"))
                                {
                                    <li>@Html.ActionLink("Assign Machines", "Index", "AssignMachines")</li>
                                }

                                @if (User.IsInRole("ProductsMachine Reload"))
                                {
                                    <li>@Html.ActionLink("Reload Products Machines", "Index", "ProductReloads")</li>
                                }
                                @if (User.IsInRole("ChangeReloads"))
                                {
                                    <li>@Html.ActionLink("Reload Changes Machines", "Index", "ChangeReloads")</li>
                                }
                            </ul>
                        </li>
                    }
                    <!-- FIM MENU MACHINES -->
                    <!-- MENU ALERT -->
                    @if (User.IsInRole("Alerts Group"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Alerts <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("HistoricAlerts"))
                                {
                                    <li>@Html.ActionLink("Historic Alert", "Index", "HistoricAlerts")</li>
                                }
                            </ul>
                        </li>
                    }
                    <!-- FIM MENU ALERT -->
                    <!-- MENU PRODUCTS -->
                    @if (User.IsInRole("Products Group"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Products <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("ProductTypes"))
                                {
                                    <li>@Html.ActionLink("Product Types", "Index", "ProductTypes")</li>
                                }
                                @if (User.IsInRole("Products"))
                                {
                                    <li>@Html.ActionLink("Product", "Index", "Products")</li>
                                }
                            </ul>
                        </li>
                    }
                    <!-- FIM MENU PRODUCTS -->
                    <!-- MENU USERS -->
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    }
                    <!-- FIM MENU USERS -->
                    <!-- MENU SELL -->
                    @if (User.IsInRole("Sells"))
                    {
                        <li>@Html.ActionLink("Sell", "Index", "Sells")</li>
                    }
                    <!-- FIM MENU SELL -->
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ehp Vending Machine</p>
        </footer>
       
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>